services:
  redis:
    image: redis:7.2
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - chat-back-office
  socket:
    image: ghcr.io/bahamut-j/chat-socket:latest
    build: ../backend/socket/
    ports:
      - 3000:3000
    networks:
      - chat-user-facing
      - chat-back-office
    environment:
      IP: "*"
      REDIS_IP: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
networks:
  chat-user-facing:
  chat-back-office:
